# Generated by Django 3.2 on 2021-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, upload_to='./../../static/img/товары/%title.png'),
        ),
    ]
